name: neurometry
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pandas
  - matplotlib
  - numpy
  - scikit-learn
  - jupyter
  - jupyterlab
  - pip:
    - black
    - giotto-ph
    - git+https://github.com/geomstats/geomstats.git
    - hyperopt==0.2.5
    - isort
    - mat73
    - pre-commit
    - pytest
    - ray[tune]
    - torch
    - wandb
    - seaborn
    - plotly
    - gdown
    - fastparquet
    - mtalg
    - torchmetrics
    - torchinfo
    - git+https://github.com/johnmarktaylor91/torchlens
    - kneed
    - jupyter-black 
    - adjustText
    - git+https://github.com/ahwillia/netrep.git
    - cupy-cuda12x

    # pyLDDMM dependencies:
    # - cycler==0.10.0
    # - decorator==4.4.1
    # - imageio==2.6.1
    # - kiwisolver==1.1.0
    # - matplotlib==3.1.2
    # - networkx==2.4
    # - Pillow==6.2.1
    # - pyparsing==2.4.6
    # - python-dateutil==2.8.1
    # - PyWavelets==1.1.1
    # - scikit-image==0.16.2
    # - scipy==1.4.1
    # - six==1.13.0
    # - numpy==1.24.3

